sudo: required
service:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_e5a9dff215e2_key -iv $encrypted_e5a9dff215e2_iv -in k8s-sample-355612-eeb991018305.json.enc -out k8s-sample-355612-eeb991018305.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file k8s-sample-355612-eeb991018305.json
  - gcloud config set project k8s-sample-355612
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster 