apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "test@test.com"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx




db.collection_name.aggregate([
  {
    $project: {
      sizeInMB: { $divide: [{ $bsonSize: "$$ROOT" }, 1024 * 1024] },
    },
  },
  {
    $match: {
      sizeInMB: { $gte: YOUR_SIZE_THRESHOLD },
    },
  },
  {
    $sort: {
      sizeInMB: -1,
    },
  },
]);
